//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.PollaExpress.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Prediction = new HashSet<Prediction>();
        }
    
        public int id { get; set; }
        public string team1 { get; set; }
        public string team2 { get; set; }
        public System.DateTime gameDate { get; set; }
        public System.TimeSpan gameHour { get; set; }
    
        public virtual ICollection<Prediction> Prediction { get; set; }
    }
}
